### ISSUE TITLE
Support the LBA 2 data in DOS format (like version from GoG.com)

### ISSUE THREAD

**Issue by pleasenophp** [agrande/lba2remake#266] opened 2020-03-04 22:16 UTC
I managed to unpack the LBA2.GOG file. It's not hard - just run the dosbox and mount the folder containing LBA2.GOG e.g. to C: drive (my paths examples are for MacOS).
`mount C "/Users/foo/myPathToFolderWithLBA2Files"`

After that mount the image to D drive
```
c:
imgmount d "LBA2.GOG" -t iso
d:
dir
```

Then you will see all the files. You need the whole LBA2 folder. To copy it recursively to C: drive where your folder is mounted you need to use some tool or script, as MS-DOS copy doesn't support recursive copy of the folders. I have used Volkov Commander from dosbox. You can grab it from here: https://archive.org/details/TheVolkovCommander_1020

So now this LBA2 folder is ready to be placed as www/data 

However, there are many issues as e.g. VOX files are not in compatible name and format. All my VOX files were named FR_000.VOX etc, while game expects FR_000_AAC.VOX, etc.

Just renaming them doesn't help - the script doesn't reconize the format, so I had to download original files from the demo web resources. The same will happen with SAMPLES_AAC.HQR that in DOS version are just SAMPLES.HQR.

After that, and after downloading some mp4 files, the game started to work for me. 

So yes, you can mostly use DOS version from GoG, but there will be some issues with some of the files. The engine is not ready to support the DOS version of LBA 2 yet, and that can be an issue for people like me that own GoG version. Maybe a separate issue should be created for this.

_Originally posted by @pleasenophp in https://github.com/agrande/lba2remake/issues/4#issuecomment-594886730_

**Comment by agrande** [comment] 2020-03-05 17:48
I'm not sure what you call the DOS format, but if I recall correctly the GOG version uses a bin/cue image like described in the original issue #4. I'm using the GOG version myself.

The VOX files are renamed because we don't have a way of decoding and playing the original audio format used in the game, so we need to extract all the HQR entries (VOX files are HQR files) convert them to a format we can use (AAC) and repackage them.

We have done it manually for our local versions and for the demo server, but the whole point of issue #4 is to find a way of doing it in code, so future contributors don't need to download it from the demo server. And it would be best if we could do this in a cross-platform way, without requiring external tools.

Feel free to tell me if I misunderstood something here. Otherwise I'll close this issue as it's basically a duplicate of #4.

**Comment by pleasenophp** [comment] 2020-03-05 18:18
> The VOX files are renamed because we don't have a way of decoding and playing the original audio format used in the game, so we need to extract all the HQR entries (VOX files are HQR files) convert them to a format we can use (AAC) and repackage them.

Ah, I didn't see anything about this step in the instructions on how to run the game locally. Is there any place where I can read it? 

What about the SAMPLES.HQR? I also had to download SAMPLES_AAC.HQR

I don't know which other files I might need in future, as I only played a few maps. But it would be nice if you can give the full instructions of what files need to be modified / repacked in the GoG version. I will try to make a script that does it automatically.

**Comment by agrande** [comment] 2020-03-05 21:38
Ok, I'll add a list of the files and what I and xesf did to convert them in the documentation.

**Closed** 2020-03-06 21:36 UTC
